### ISSUE TITLE
Game crashes if i respawn at the core or start a wave at greyland

### ISSUE THREAD

**Issue by le-emone** [3Snake3/ADC#15]
Everytime i respawn at the core game crashes and leaving a crash report. Same happens after wave 3 or 4 in greyland. P.S. sorry if there is mistakes in wy language.
Crash report:

Mindustry has crashed. How unfortunate.
Version: release build 143
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 4032mb
Cores: 16
Mods: betamindy:1.09
[#b59e72]Demo of Chaos Itself[], better-vaults:1.1, cyber-io:5.1-erekir, exogenesis:[blue]1.9.1, extended-ui:0.75, major:2.4, me:2.1, morevanilla:1.3, multi-crafter:1.0, new-horizon:0.3.0, sapphirium:16.0, schemepack:1, time-control:0.2

rhino.EcmaError: TypeError: Cannot call property controller in object Unit#20285509:sapphirium-lambda. It is not a function, it is "object". (draw-cycle#33)
	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3741)
	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3721)
	at rhino.ScriptRuntime.typeError(ScriptRuntime.java:3750)
	at rhino.ScriptRuntime.typeError3(ScriptRuntime.java:3772)
	at rhino.ScriptRuntime.notFunctionError(ScriptRuntime.java:3832)
	at rhino.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2192)
	at rhino.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2175)
	at rhino.optimizer.OptRuntime.callProp0(OptRuntime.java:69)
	at rhino.gen.draw_cycle_67._c_anonymous_2(draw-cycle:33)
	at rhino.gen.draw_cycle_67.call(draw-cycle)
	at rhino.ArrowFunction.call(ArrowFunction.java:33)
	at rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:141)
	at rhino.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:92)
	at rhino.Context.call(Context.java:450)
	at rhino.ContextFactory.call(ContextFactory.java:428)
	at rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:92)
	at rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:142)
	at jdk.proxy1/jdk.proxy1.$Proxy2.get(Unknown Source)
	at mindustry.entities.EntityGroup.each(EntityGroup.java:94)
	at jdk.internal.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at rhino.MemberBox.invoke(MemberBox.java:104)
	at rhino.NativeJavaMethod.call(NativeJavaMethod.java:205)
	at rhino.optimizer.OptRuntime.call1(OptRuntime.java:23)
	at rhino.gen.draw_cycle_67._c_anonymous_1(draw-cycle:18)
	at rhino.gen.draw_cycle_67.call(draw-cycle)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:328)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3114)
	at rhino.gen.draw_cycle_67.call(draw-cycle)
	at rhino.ArrowFunction.call(ArrowFunction.java:33)
	at rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:141)
	at rhino.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:92)
	at rhino.Context.call(Context.java:450)
	at rhino.ContextFactory.call(ContextFactory.java:428)
	at rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:92)
	at rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:142)
	at jdk.proxy2/jdk.proxy2.$Proxy3.run(Unknown Source)
	at arc.Events.lambda$run$2(Events.java:20)
	at arc.Events.fire(Events.java:36)
	at mindustry.core.Renderer.draw(Renderer.java:308)
	at mindustry.core.Renderer.update(Renderer.java:224)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:228)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by 3Snake3** [comment]
Let me check

**Comment by 3Snake3** [comment]
Hmm... I can't reproduce it, but I'll to do something

**Comment by le-emone** [comment]
thank you for the response
btw i noticed that it happens only in campaign

**Comment by 3Snake3** [comment]
> Everytime i respawn at the core game crashes and leaving a crash report. Same happens after wave 3 or 4 in greyland. P.S. sorry if there is mistakes in wy language.
> Crash report:
> 
> 
> Mindustry has crashed. How unfortunate.
> Version: release build 143
> OS: Windows 10 x64 (amd64)
> Java Version: 16.0.1
> Runtime Available Memory: 4032mb
> Cores: 16
> Mods: betamindy:1.09
> [#b59e72]Demo of Chaos Itself[], better-vaults:1.1, cyber-io:5.1-erekir, exogenesis:[blue]1.9.1, extended-ui:0.75, major:2.4, me:2.1, morevanilla:1.3, multi-crafter:1.0, new-horizon:0.3.0, sapphirium:16.0, schemepack:1, time-control:0.2
> 
> rhino.EcmaError: TypeError: Cannot call property controller in object Unit#20285509:sapphirium-lambda. It is not a function, it is "object". (draw-cycle#33)
> 	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3741)
> 	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3721)
> 	at rhino.ScriptRuntime.typeError(ScriptRuntime.java:3750)
> 	at rhino.ScriptRuntime.typeError3(ScriptRuntime.java:3772)
> 	at rhino.ScriptRuntime.notFunctionError(ScriptRuntime.java:3832)
> 	at rhino.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2192)
> 	at rhino.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2175)
> 	at rhino.optimizer.OptRuntime.callProp0(OptRuntime.java:69)
> 	at rhino.gen.draw_cycle_67._c_anonymous_2(draw-cycle:33)
> 	at rhino.gen.draw_cycle_67.call(draw-cycle)
> 	at rhino.ArrowFunction.call(ArrowFunction.java:33)
> 	at rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:141)
> 	at rhino.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:92)
> 	at rhino.Context.call(Context.java:450)
> 	at rhino.ContextFactory.call(ContextFactory.java:428)
> 	at rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:92)
> 	at rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:142)
> 	at jdk.proxy1/jdk.proxy1.$Proxy2.get(Unknown Source)
> 	at mindustry.entities.EntityGroup.each(EntityGroup.java:94)
> 	at jdk.internal.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at rhino.MemberBox.invoke(MemberBox.java:104)
> 	at rhino.NativeJavaMethod.call(NativeJavaMethod.java:205)
> 	at rhino.optimizer.OptRuntime.call1(OptRuntime.java:23)
> 	at rhino.gen.draw_cycle_67._c_anonymous_1(draw-cycle:18)
> 	at rhino.gen.draw_cycle_67.call(draw-cycle)
> 	at rhino.ContextFactory.doTopCall(ContextFactory.java:328)
> 	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3114)
> 	at rhino.gen.draw_cycle_67.call(draw-cycle)
> 	at rhino.ArrowFunction.call(ArrowFunction.java:33)
> 	at rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:141)
> 	at rhino.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:92)
> 	at rhino.Context.call(Context.java:450)
> 	at rhino.ContextFactory.call(ContextFactory.java:428)
> 	at rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:92)
> 	at rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:142)
> 	at jdk.proxy2/jdk.proxy2.$Proxy3.run(Unknown Source)
> 	at arc.Events.lambda$run$2(Events.java:20)
> 	at arc.Events.fire(Events.java:36)
> 	at mindustry.core.Renderer.draw(Renderer.java:308)
> 	at mindustry.core.Renderer.update(Renderer.java:224)
> 	at arc.ApplicationCore.update(ApplicationCore.java:37)
> 	at mindustry.ClientLauncher.update(ClientLauncher.java:228)
> 	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
> 	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
> 	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
> 	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

Reinstall the mod and try again

**Comment by le-emone** [comment]
same thing happens
i did some tests and it happens only with core cage 
sorry for not telling everything from the start it's my first bug report and i don't really know how to make it properly

**Comment by 3Snake3** [comment]
> same thing happens
> i did some tests and it happens only with core cage 
> sorry for not telling everything from the start it's my first bug report and i don't really know how to make it properly
> 

Send crash log again

**Comment by le-emone** [comment]
[crash-report-04_02_2023_08_49_20.txt](https://github.com/3Snake3/Sapphirium/files/11131368/crash-report-04_02_2023_08_49_20.txt)
it's a crash log from later but with the same problem

**Comment by 3Snake3** [comment]
> [crash-report-04_02_2023_08_49_20.txt](https://github.com/3Snake3/Sapphirium/files/11131368/crash-report-04_02_2023_08_49_20.txt)
> it's a crash log from later but with the same problem
> 

Delete the mod and install again

**Comment by le-emone** [comment]
didn't help

**Comment by 3Snake3** [comment]
> didn't help

It's very strange... I can't reproduce the problem even in the campaign, Lambda respawns well, on all waves
What device are you playing on?

**Comment by le-emone** [comment]
pc (asus tuf gaming f15)

**Comment by le-emone** [comment]
i found the problem
saphirium is conflicting with extended ui mod.
sorry for wasting your time on this bug

**Comment by 3Snake3** [comment]
> i found the problem
> saphirium is conflicting with extended ui mod.
> sorry for wasting your time on this bug
> 

Don't worry, its ok
