### ISSUE TITLE
Placing down 'Armed Ice Cube' causes crash

### ISSUE THREAD

**Issue by Mac33299** [3Snake3/ADC#18]
I don't really know why. but my game crashes whenever I placed them down

Crash report:

Mindustry has crashed. How unfortunate.
Version: release build 143.1
OS: Windows 10 x64 (amd64)
Java Version: 1.8.0_351
Runtime Available Memory: 1796mb
Cores: 8
Mods: informatis:1.7, sapphirium:16.0

java.lang.NullPointerException
	at informatis.ui.windows.BarInfo.getInfo(UnitWindow.java:436)
	at informatis.ui.windows.UnitWindow.lambda$new$0(UnitWindow.java:77)
	at arc.Events.lambda$run$2(Events.java:20)
	at arc.Events.fire(Events.java:36)
	at mindustry.core.Logic.update(Logic.java:403)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:228)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by 3Snake3** [comment]
Perhaps this is a conflict between mods... Send in addition last_log

**Comment by Mac33299** [comment]
hmm... that seem to be the case...

**Comment by 3Snake3** [comment]
> hmm... that seem to be the case...

I guess why this is happening. Give me time, I'll try to fix it.

**Comment by 3Snake3** [comment]
@Mac33299 I reproduced the issue and fixed it successfully
